### ISSUE TITLE
Improved privacy settings

### ISSUE THREAD

**Issue by ikreymer** [Rhizome-Conifer/conifer#1]
Private collections:
- Ability to share collection with specific users only

Public collections:
- Ability to make semi-private, restrict 'discovery' but not access..
- Does restricting access but not discovery make sense? (Maybe?)

Discovery would include: records tab, search, /*/ page listings

**Comment by almereyda** [comment]
Is there a way for me to understand, as an outside visitor of the project, why this issue had been closed?

Would the previous comment mean, that a collection's link is considered 'an open secret', and it cannot be discovered in any other way than sharing through copy and paste from the address bar, while it does not appear in any other listing anywhere else?
