### ISSUE TITLE
Support full text search!

### ISSUE THREAD

**Issue by ikreymer** [Rhizome-Conifer/conifer#3]
Automated indexing of warcs as they are archived, to allow users to search for any text content as soon as it was recorded.

Consider various backends: elasticsearch is a major one, but there's also Xapian and Whoosh (entirely python based!)

**Comment by norstbox** [comment]
Full text search is an important feature for such platform. Do you have plans for its implementation in the foreseeable future? Or is this feature still low priority for the project?

**Comment by m4rk3r** [comment]
Hi @norstbox we've recently rolled out a full-text search feature, read more about it here: https://blog.conifer.rhizome.org/2021/04/29/search-and-curation-updates.html
