### ISSUE TITLE
docker install, missing admin interface

### ISSUE THREAD

**Issue by jotjot** [Rhizome-Conifer/conifer#555]
The docker install went fine on Mac OS. Afterwards I created an admin user via the command line, as shown in the documentation. When I login I see the link to the admin interface, but when I click on it I get an "500 internal server error". Any ideas?

**Comment by kzahel** [comment]
I ran into the same problem. I am using docker-compose. Which container should I jump into to run the build script? Any chance this can be a configurable option to include the admin asset build in the docker-compose setup?

**Comment by m4rk3r** [comment]
Hi @kzahel sorry for the lack of detail on this.. you can build the admin from within the `app` container, e.g. `docker exec -it -u root webrecorder_app_1 bash` and then run `sh admin/build.sh` or this _should_ also tigger a build from outside the container `docker exec -it webrecorder_app_1 sh admin.build` (untested)

We've undergone a major overhaul, currently on develop branch and also deployed on webrecorder.io, and part of that is simplifying the admin interface and integrating it with the main UI. We'll be merging that into master shortly, and will have a migration guide with more info.

Are you using the admin interface primarily for managing users, or for the stats and other info?
