### ISSUE TITLE
Specify alternate root directory in desktop app

### ISSUE THREAD

**Issue by nickpunt** [Rhizome-Conifer/conifer#793]
*(This is written from point of view of MacOS version)*

There doesn't seem to be any way to change or select an alternate root directory for Webrecorder-Data in the desktop app UI. 

The use case for this capability is a) to move directories to Dropbox or other cloud sync'd folders, to reduce the chance of data loss, and b) to support easier sharing for collaborators collecting data together on those services.

Ideally, this would be available on a per-collection basis from within the Manage Collection page, as the use case of collections may be for different personal or professional projects that have pre-existing directory structures. 

If a smaller scope is preferred, setting the global Data Directory would get far enough along. The change would be pretty minor: 
- [ ] In App Settings, change the Data Directory link to open a directory picker window (with 'Cancel / Choose' buttons), rather than simply opening Finder to that directory.
<img width="374" alt="Screen Shot 2020-05-11 at 3 43 03 PM" src="https://user-images.githubusercontent.com/88428/81619295-1da9bb00-939e-11ea-8d43-5ae0c44941e5.png">

Meanwhile, existing functionality of reverting back to default (/Documents/Webrecorder-Data) would still work if the user specified directory is no longer found.

**Comment by m4rk3r** [comment]
Hi @nickpunt, thanks for raising this issue. This is indeed a good suggestion, would you mind opening it on the [Webrecorder Desktop](https://github.com/webrecorder/webrecorder-desktop) repo?
