### ISSUE TITLE
Frontend file-loader, mini-css, react Issue

### ISSUE THREAD

**Issue by A75G** [Rhizome-Conifer/conifer#794]
Hello,
I tried  running webrecorder on digitalocean and local-pc 
Both have same problem the error below
I would be grateful for anyone who can tell me whats the problem

`warning file-loader@2.0.0: Invalid bin field for "file-loader".                                                         warning mini-css-extract-plugin@0.4.5: Invalid bin field for "mini-css-extract-plugin".                                 warning url-loader@1.1.2: Invalid bin field for "url-loader".                                                           info fsevents@1.2.4: The platform "linux" is incompatible with this module.                                             info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.         info fsevents@1.2.9: The platform "linux" is incompatible with this module.                                             info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.         [4/5] Linking dependencies...                                                                                           warning " > react-router-breadcrumbs-hoc@1.1.3" has unmet peer dependency "react-router@^4.2.0".                        warning " > react-router-config@4.4.0-beta.6" has unmet peer dependency "react-router@4.4.0-beta.1".                    warning " > redux-connect@8.0.0" has unmet peer dependency "react-router@4.x.x".                                        warning " > redux-connect@8.0.0" has incorrect peer dependency "react-router-config@1.x.x || ^1.0.0-beta".`

**Comment by m4rk3r** [comment]
Hi @A75G those are just warnings and shouldn't blocking webrecorder from running.
What steps are you taking to launch everything? There is a bit of a delay for the first build, so also worth trying `http://localhost:8089` after a minute or so.

When you `docker ps` do you see all these containers running?
```
NAMES
nginx
behaviors
frontend
app
recorder
shepherd
warcserver
redis
```
Any helpful output with `docker logs app` or `docker logs frontend`?

**Comment by A75G** [comment]
docker ps 
```
frontend
shepherd
behaviors
redis
mailserver
coturn
```
missing
```
recorder
nginx
app
shepherd
```

**Comment by m4rk3r** [comment]
Frontend output looks good.. likely something wrong with the app container, can you share that log?

**Comment by A75G** [comment]
> 
> 
> Frontend output looks good.. likely something wrong with the app container, can you share that log?

i cant because it was missing when i put docker ps
i tried docker-compose down then up 
nothing keep up
Thank you for the quick reply

**Comment by m4rk3r** [comment]
Just wanted to double check, you're following these instructions, right? https://github.com/webrecorder/webrecorder#running-locally

What kind of output do you get running `docker-compose up app`?
