### ISSUE TITLE
Stuck in Maintenance Mod (first Run)

### ISSUE THREAD

**Issue by mutlurasit** [Rhizome-Conifer/conifer#799]
Hello, 

I have recently installed webrecorder to a AWS EC2 on Ubuntu 16.04. with Docker. Instillation went smooth but it stuck on maintenance mod for about an hour now.

Is there anything I might be missing?

Here is the running "things" when I put `docker ps`

  	                      
webrecorder/nginx              
webrecorder_recorder           
oldwebtoday/shepherd:1.2.0     
webrecorder_warcserver                                                      
oldwebtoday/coturn:1.0         
webrecorder/behaviors:latest   
webrecorder_redis                                                        
catatnight/postfix
`
p.s. I am not familiar with any of this so apologies if this is stupidly simple. I am happy to provide more info if needed.

**Comment by m4rk3r** [comment]
Hm, seems the `frontend` isn't running, can you see if there's anything helpful there w/ `docker logs frontend`?

**Comment by mutlurasit** [comment]
@m4rk3r tank you very much for your response. 

turns this message:  

running production build

> webrecorder-frontend@1.0.0 docker-prod /code
> run-s prod:client:build prod:server:build docker-prod:server:start


> webrecorder-frontend@1.0.0 prod:client:build /code
> webpack --config ./webpack/webpack.config.client.production.babel.js

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! webrecorder-frontend@1.0.0 prod:client:build: `webpack --config ./webpack/webpack.config.client.production.babel.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the webrecorder-frontend@1.0.0 prod:client:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-17T17_47_47_376Z-debug.log
ERROR: "prod:client:build" exited with 137.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webrecorder-frontend@1.0.0 docker-prod: `run-s prod:client:build prod:server:build docker-prod:server:start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webrecorder-frontend@1.0.0 docker-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-17T17_47_47_447Z-debug.log
running production build

> webrecorder-frontend@1.0.0 docker-prod /code
> run-s prod:client:build prod:server:build docker-prod:server:start


> webrecorder-frontend@1.0.0 prod:client:build /code
> webpack --config ./webpack/webpack.config.client.production.babel.js

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! webrecorder-frontend@1.0.0 prod:client:build: `webpack --config ./webpack/webpack.config.client.production.babel.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the webrecorder-frontend@1.0.0 prod:client:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-17T18_24_25_241Z-debug.log
ERROR: "prod:client:build" exited with 137.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webrecorder-frontend@1.0.0 docker-prod: `run-s prod:client:build prod:server:build docker-prod:server:start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webrecorder-frontend@1.0.0 docker-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-17T18_24_25_409Z-debug.log

**Comment by m4rk3r** [comment]
hmm, could you try doing a full rebuild:
`docker-compose kill frontend; docker-compose rm -f frontend; docker-compose build --no-cache frontend; docker-compose up -d frontend`

and see if you get the same result?

**Comment by mutlurasit** [comment]
when i put the code it returned

ubuntu@ip-172-31-38-12:~/webrecorder$ sudo docker-compose kill frontend; docker-compose rm -f frontend; docker-compose build --no-cache frontend; docker-compose up -d frontend
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Building frontend
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by mutlurasit** [comment]
ok i tried to run each code separate as in 

1. docker-compose rm -f frontend

this worked fine and removed

2. docker-compose build --no-cache frontend

 this returned the following error (same as in the initial setup)

[3/5] Fetching packages...
warning file-loader@2.0.0: Invalid bin field for "file-loader".
warning mini-css-extract-plugin@0.4.5: Invalid bin field for "mini-css-extract-plugin".
warning url-loader@1.1.2: Invalid bin field for "url-loader".
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > react-router-breadcrumbs-hoc@1.1.3" has unmet peer dependency "react-router@^4.2.0".
warning " > react-router-config@4.4.0-beta.6" has unmet peer dependency "react-router@4.4.0-beta.1".
warning " > redux-connect@8.0.0" has unmet peer dependency "react-router@4.x.x".
warning " > redux-connect@8.0.0" has incorrect peer dependency "react-router-config@1.x.x || ^1.0.0-beta".
^CERROR: Aborting.

**Comment by m4rk3r** [comment]
That output all looks ok, did you kill it at the end there? seeing the `^C ERROR: Aboring`

**Comment by mutlurasit** [comment]
yes, that was me i think. i run the code but could build frontend

ERROR: Service 'frontend' failed to build: The command '/bin/sh -c rm -rf node_modules && yarn install                                  && yarn cache clean && rm -rf ~/tmp/*' returned a non-zero code: 1

**Comment by mutlurasit** [comment]
also this when i put docker-compose up -d frontend

Creating frontend ...

ERROR: for frontend  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for frontend  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher

**Comment by mutlurasit** [comment]
I am sorry, I have been trying many different things always stuck on the point, always on maintenance mode. Could that be a memory issue by ant chance? I am on a AWS free tier for now (so only 1 GB memory)

**Comment by mutlurasit** [comment]
FINAL UPDATE

yes, this was a memory issue as far as I can tell. I upgraded to t3.medium on AWS and worked without a single issue.

**Comment by m4rk3r** [comment]
@mutlurasit ah good to hear, yes it will likely require more than a micro to run.. glad you got it up!

**Comment by mutlurasit** [comment]
@m4rk3r yeah some minimum requirement info would be really helpful. thanks for this amazing project by the way.
