### ISSUE TITLE
Twitter rate limiting problem?

### ISSUE THREAD

**Issue by zpelli3** [Rhizome-Conifer/conifer#801]
It seems like I am unable to capture any twitter page at all. As soon as I hit "Capture" I get a white screen with the message "Too Many Requests". Is there some sort of global limit on twitter crawls?

**Comment by ikreymer** [comment]
Yes, this is a known issue. Unfortunately, not much that can be done on the hosted service.
Please use the [Webrecorder Desktop](https://github.com/webrecorder/webrecorder-desktop/releases) app if you want to archive twitter pages.

**Comment by zpelli3** [comment]
Thanks!
